use std::path::Path;

use anyhow::{Context, Result};

use crate::models::{HostResult, HostStatus, PortState, ScanResult};

pub fn write_html_file(result: &ScanResult, path: &str) -> Result<()> {
    let html = generate_html(result);
    std::fs::write(Path::new(path), &html)
        .with_context(|| format!("Failed to write HTML report to {path}"))?;
    eprintln!("[*] HTML report written to {path}");
    Ok(())
}

fn generate_html(result: &ScanResult) -> String {
    let hosts_up: Vec<&HostResult> = result
        .hosts
        .iter()
        .filter(|h| h.status == HostStatus::Up)
        .collect();

    let network_svg = generate_network_svg(&hosts_up);
    let host_cards = hosts_up
        .iter()
        .map(|h| generate_host_card(h))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>nmapper Scan Report — {target}</title>
<style>
:root {{
  --bg: #0d1117;
  --card: #161b22;
  --border: #30363d;
  --text: #c9d1d9;
  --text-dim: #8b949e;
  --accent: #58a6ff;
  --green: #3fb950;
  --red: #f85149;
  --yellow: #d29922;
  --purple: #bc8cff;
  --cyan: #39d2c0;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem;
}}
.container {{ max-width: 1200px; margin: 0 auto; }}
h1 {{ color: var(--accent); margin-bottom: 0.5rem; font-size: 1.5rem; }}
.meta {{ color: var(--text-dim); margin-bottom: 2rem; font-size: 0.9rem; }}
.meta span {{ margin-right: 1.5rem; }}
.summary {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}}
.stat {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  text-align: center;
}}
.stat .value {{ font-size: 2rem; font-weight: bold; color: var(--accent); }}
.stat .label {{ font-size: 0.85rem; color: var(--text-dim); }}
.network-map {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  margin-bottom: 2rem;
  text-align: center;
  overflow-x: auto;
}}
.network-map h2 {{ color: var(--text); margin-bottom: 1rem; font-size: 1.1rem; }}
.host-card {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1rem;
}}
.host-header {{
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 0.5rem;
  flex-wrap: wrap;
}}
.host-ip {{ font-size: 1.2rem; font-weight: bold; color: var(--cyan); }}
.host-hostname {{ color: var(--text-dim); }}
.host-mac {{ color: var(--text-dim); font-size: 0.85rem; }}
.host-vendor {{ color: var(--purple); font-size: 0.85rem; }}
.host-mdns {{ color: var(--yellow); font-size: 0.85rem; }}
.badge {{
  display: inline-block;
  padding: 0.15rem 0.5rem;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: bold;
}}
.badge-up {{ background: rgba(63,185,80,0.15); color: var(--green); }}
.badge-os {{ background: rgba(188,140,255,0.15); color: var(--purple); }}
table {{
  width: 100%;
  border-collapse: collapse;
  margin-top: 0.75rem;
  font-size: 0.9rem;
}}
th {{
  text-align: left;
  padding: 0.5rem 0.75rem;
  border-bottom: 2px solid var(--border);
  color: var(--text-dim);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}
td {{
  padding: 0.4rem 0.75rem;
  border-bottom: 1px solid var(--border);
}}
tr:last-child td {{ border-bottom: none; }}
.port-open {{ color: var(--green); }}
.port-closed {{ color: var(--red); }}
.port-filtered {{ color: var(--yellow); }}
.footer {{
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  color: var(--text-dim);
  font-size: 0.85rem;
  text-align: center;
}}
</style>
</head>
<body>
<div class="container">
<h1>nmapper Scan Report</h1>
<div class="meta">
  <span>Target: {target}</span>
  <span>Scan type: {scan_type}</span>
  <span>Duration: {duration:.2}s</span>
  <span>Date: {date}</span>
</div>

<div class="summary">
  <div class="stat"><div class="value">{hosts_scanned}</div><div class="label">Hosts Scanned</div></div>
  <div class="stat"><div class="value" style="color:var(--green)">{hosts_up}</div><div class="label">Hosts Up</div></div>
  <div class="stat"><div class="value" style="color:var(--red)">{hosts_down}</div><div class="label">Hosts Down</div></div>
  <div class="stat"><div class="value">{ports_scanned}</div><div class="label">Ports Scanned</div></div>
</div>

<div class="network-map">
<h2>Network Map</h2>
{network_svg}
</div>

{host_cards}

<div class="footer">
  Generated by nmapper v{version}
</div>
</div>
</body>
</html>"#,
        target = html_escape(&result.scan_info.target_spec),
        scan_type = html_escape(&result.scan_info.scan_type),
        duration = result.scan_info.duration_secs,
        date = html_escape(&result.scan_info.start_time),
        hosts_scanned = result.scan_info.total_hosts_scanned,
        hosts_up = result.scan_info.hosts_up,
        hosts_down = result.scan_info.total_hosts_scanned - result.scan_info.hosts_up,
        ports_scanned = result.scan_info.total_ports_scanned,
        network_svg = network_svg,
        host_cards = host_cards,
        version = env!("CARGO_PKG_VERSION"),
    )
}

fn generate_host_card(host: &HostResult) -> String {
    let hostname = host
        .hostname
        .as_ref()
        .map(|h| format!(r#"<span class="host-hostname">({})</span>"#, html_escape(h)))
        .unwrap_or_default();

    let mac_line = host
        .mac_address
        .as_ref()
        .map(|mac| {
            let vendor = host
                .vendor
                .as_ref()
                .map(|v| format!(r#" <span class="host-vendor">{}</span>"#, html_escape(v)))
                .unwrap_or_default();
            format!(
                r#"<div class="host-mac">MAC: {}{}</div>"#,
                html_escape(&mac.to_string()),
                vendor
            )
        })
        .unwrap_or_default();

    let mdns_line = host
        .mdns_names
        .as_ref()
        .filter(|n| !n.is_empty())
        .map(|names| {
            format!(
                r#"<div class="host-mdns">mDNS: {}</div>"#,
                html_escape(&names.join(", "))
            )
        })
        .unwrap_or_default();

    let os_badge = host
        .os
        .as_ref()
        .map(|os| {
            format!(
                r#"<span class="badge badge-os">{} ({:.0}%)</span>"#,
                html_escape(&os.name),
                os.confidence * 100.0
            )
        })
        .unwrap_or_default();

    let open_ports: Vec<_> = host
        .ports
        .iter()
        .filter(|p| p.state == PortState::Open)
        .collect();

    let port_table = if open_ports.is_empty() {
        r#"<p style="color:var(--text-dim);margin-top:0.5rem">No open ports found.</p>"#
            .to_string()
    } else {
        let rows: Vec<String> = open_ports
            .iter()
            .map(|p| {
                let state_class = match p.state {
                    PortState::Open => "port-open",
                    PortState::Closed => "port-closed",
                    PortState::Filtered => "port-filtered",
                };
                let svc_name = p
                    .service
                    .as_ref()
                    .map(|s| html_escape(&s.name))
                    .unwrap_or_else(|| "-".to_string());
                let svc_ver = p
                    .service
                    .as_ref()
                    .and_then(|s| s.version.as_ref())
                    .map(|v| html_escape(v))
                    .unwrap_or_else(|| "-".to_string());
                format!(
                    r#"<tr><td>{}/{}</td><td class="{}">{}</td><td>{}</td><td>{}</td></tr>"#,
                    p.port, p.protocol, state_class, p.state, svc_name, svc_ver
                )
            })
            .collect();

        format!(
            r#"<table>
<thead><tr><th>Port</th><th>State</th><th>Service</th><th>Version</th></tr></thead>
<tbody>{}</tbody>
</table>"#,
            rows.join("\n")
        )
    };

    let closed = host.ports.iter().filter(|p| p.state == PortState::Closed).count();
    let filtered = host.ports.iter().filter(|p| p.state == PortState::Filtered).count();
    let not_shown = if closed > 0 || filtered > 0 {
        let mut parts = Vec::new();
        if closed > 0 {
            parts.push(format!("{closed} closed"));
        }
        if filtered > 0 {
            parts.push(format!("{filtered} filtered"));
        }
        format!(
            r#"<p style="color:var(--text-dim);font-size:0.85rem;margin-top:0.25rem">Not shown: {}</p>"#,
            parts.join(", ")
        )
    } else {
        String::new()
    };

    format!(
        r#"<div class="host-card">
<div class="host-header">
  <span class="host-ip">{ip}</span>
  {hostname}
  <span class="badge badge-up">up</span>
  {os_badge}
</div>
{mac_line}
{mdns_line}
{port_table}
{not_shown}
</div>"#,
        ip = host.ip,
        hostname = hostname,
        os_badge = os_badge,
        mac_line = mac_line,
        mdns_line = mdns_line,
        port_table = port_table,
        not_shown = not_shown,
    )
}

fn generate_network_svg(hosts: &[&HostResult]) -> String {
    if hosts.is_empty() {
        return r#"<p style="color:var(--text-dim)">No hosts to display.</p>"#.to_string();
    }

    let count = hosts.len();
    let radius = if count <= 4 {
        120.0
    } else if count <= 10 {
        180.0
    } else {
        240.0
    };
    let cx = radius + 80.0;
    let cy = radius + 80.0;
    let width = (cx + radius + 80.0) as u32;
    let height = (cy + radius + 80.0) as u32;

    let mut svg = String::new();
    svg.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {width} {height}\" style=\"max-width:{width}px;width:100%\">"
    ));

    let text_y = cy + 4.0;
    svg.push_str(&format!(
        "<circle cx=\"{cx}\" cy=\"{cy}\" r=\"30\" fill=\"#1f6feb\" stroke=\"#58a6ff\" stroke-width=\"2\"/>\
         <text x=\"{cx}\" y=\"{text_y}\" text-anchor=\"middle\" fill=\"white\" font-size=\"10\" font-weight=\"bold\">Network</text>"
    ));

    for (i, host) in hosts.iter().enumerate() {
        let angle = (2.0 * std::f64::consts::PI * i as f64) / count as f64
            - std::f64::consts::FRAC_PI_2;
        let hx = cx + radius * angle.cos();
        let hy = cy + radius * angle.sin();

        let open_ports = host
            .ports
            .iter()
            .filter(|p| p.state == PortState::Open)
            .count();

        let (fill, stroke_c) = if let Some(ref os) = host.os {
            match os.name.as_str() {
                n if n.contains("Linux") => ("#2ea043", "#3fb950"),
                n if n.contains("Windows") => ("#1f6feb", "#58a6ff"),
                n if n.contains("macOS") || n.contains("iOS") => ("#8b949e", "#c9d1d9"),
                n if n.contains("IoT") || n.contains("Network") => ("#d29922", "#e3b341"),
                _ => ("#6e7681", "#8b949e"),
            }
        } else if open_ports > 5 {
            ("#bc8cff", "#d2a8ff")
        } else {
            ("#39d2c0", "#56d4c8")
        };

        let node_r = if open_ports > 10 {
            22.0
        } else if open_ports > 3 {
            18.0
        } else {
            14.0
        };

        svg.push_str(&format!(
            "<line x1=\"{cx}\" y1=\"{cy}\" x2=\"{hx}\" y2=\"{hy}\" stroke=\"#30363d\" stroke-width=\"1\"/>"
        ));

        svg.push_str(&format!(
            "<circle cx=\"{hx}\" cy=\"{hy}\" r=\"{node_r}\" fill=\"{fill}\" stroke=\"{stroke_c}\" stroke-width=\"2\"/>"
        ));

        let ip_str = host.ip.to_string();
        let short_ip = ip_str.rsplit('.').next().unwrap_or(&ip_str);
        let label_y = hy + 3.0;
        svg.push_str(&format!(
            "<text x=\"{hx}\" y=\"{label_y}\" text-anchor=\"middle\" fill=\"white\" font-size=\"8\" font-weight=\"bold\">.{short_ip}</text>"
        ));

        let label = host
            .vendor
            .as_deref()
            .or(host.hostname.as_deref())
            .unwrap_or("");
        if !label.is_empty() {
            let short_label = if label.len() > 16 {
                &label[..16]
            } else {
                label
            };
            let name_y = hy + node_r + 12.0;
            svg.push_str(&format!(
                "<text x=\"{hx}\" y=\"{name_y}\" text-anchor=\"middle\" fill=\"#8b949e\" font-size=\"7\">{}</text>",
                html_escape(short_label),
            ));
        }

        if open_ports > 0 {
            let port_y = hy + node_r + if label.is_empty() { 12.0 } else { 22.0 };
            let suffix = if open_ports == 1 { "" } else { "s" };
            svg.push_str(&format!(
                "<text x=\"{hx}\" y=\"{port_y}\" text-anchor=\"middle\" fill=\"#3fb950\" font-size=\"7\">{open_ports} port{suffix}</text>"
            ));
        }
    }

    svg.push_str("</svg>");
    svg
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
